### ISSUE TITLE
Gaussian Restart examples with COM files

### ISSUE THREAD

**Issue by plstonge** [ComputeCanada/docs#5]
In the Gaussian page:
https://docs.computecanada.ca/wiki/Gaussian

We are missing COM files examples to restart a stopped job. See also Ticket#099291.

Sharcnet has some examples and instructions. We need a full example when the RWF is not defined on the first run (apparently, this goes to /scratch/username/jobid/filename.rwf, but it needs to be moved one folder up before resuming the job) and another example when the RWF is defined at every step:
https://www.sharcnet.ca/help/index.php/GAUSSIAN#Restart

Finally, what is best: %NoSave or %ErrorSave?

**Comment by stubbsda** [comment]
The best person to ask for that may be Jemmy Hu - he's likely the person responsible for most of the current Sharcnet documentation on Gaussian. We just need to ask him to copy the Gaussian material over to the CC Wiki where it can then be translated into French.

**Comment by plstonge** [comment]
Right. He also has Gaussian job samples in his home directory on Graham. See Ticket#099291, message #7.

**Comment by stubbsda** [comment]
Hi Pier-Luc,
  I am checking up on this matter as Jemmy is back from vacation these days I think. Concerning the example files, I believe they are now under /opt/software/gaussian/<version>/examples on the relevant clusters (Cedar and Graham) rather than being in his home directory. I will contact Jemmy (or Pawel, a Sharcnet guy who's on the RSNT) to see about getting the Sharcnet material copied over to the CC Wiki.
Regards,
  Daniel

**Comment by stubbsda** [comment]
A new section on restarting Gaussian jobs has been added to the Wiki page by Jemmy and I've marked it for translation into French.
