### ISSUE TITLE
Installing a better search engine

### ISSUE THREAD

**Issue by mboisson** [ComputeCanada/docs#7]
Possible extensions : 
AdvancedSearch extension (based on Cyrus search engine). 
Update: AdvancedSearch + CirrusSearch + Elastica + ElasticSearch is installed on docs-dev. Required Java installation and PhP with curl support.
https://docs-dev.computecanada.ca/wiki/Special:Search

Also need to look into possibly embedding Google search. 
Update: currently in progress. Installed GoogleCustomWikiSearch on docs-dev, trying to configure it, etc.

**Comment by mboisson** [comment]
Possible options : 
https://support.google.com/programmable-search/thread/12870434?hl=en
https://support.google.com/programmable-search/answer/9069107

https://support.google.com/programmable-search/answer/4542102

**Comment by sergueev** [comment]
The Google search engine has been activated (by Sergiy) . Here is the link to the CSE control page:
https://cse.google.com/cse/setup/basic?cx=fc42fa4fd6b87fb36
After that I have installed two MW extensions: SecureHTML and GoogleSiteSearch. Using the SecureHTML I was able to include the HTML code for the search box provided by Google into the body of the page's header. Now such a search box appears at the top of every page. This has been done with the help of ArticleViewHeader hook. This search HTML code does the search and then output the result into the separate page wiki/Compute_Canada_Search . 
The same functionality can be accomplished by the GoogleSiteSearch extension. The only difference is that the later uses the usual/default search box located in the top frame together with the google search engine instead of MW default one to populate the Special page with the search results.
Perhaps we may need to decide which of those above methods is more appropriate for us.

**Comment by mboisson** [comment]
I think this can be closed ?

**Comment by sergueev** [comment]
The Google search engine has been installed on docs with the help of GoogleSiteSearch extension. We also added two other sites including computecanada.ca and status.computecanada.ca. Everything seems to be functional, no problems have been reported so far. Closing this issue for now.
